version: '3.9'

services:
  students:
    build: ./students_service
    ports:
      - "8000:80"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/__health" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s

  books:
    build: ./books_service
    ports:
      - "8001:80"

  krakend_ce:
    image: devopsfaith/krakend:watch
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "8080:8080"
    command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]
    depends_on:
      - students
      - books